FROM node:20-alpine As base
RUN apk add --no-cache libc6-compat

# Install dependencies only when needed
FROM base AS deps
WORKDIR /opt/app
COPY . ./
RUN npm install && \
    npm run build
CMD ["npm", "run", "start"]